ghost_nginx:
  restart: always
  build: ./ghostNginx/
  ports:
    - 80:80
    - 443:443
  links:
    - 'ghostblog:ghostblog'

ghostblog:
  container_name: petemsGhost
  build: ./petemsGhost/
  restart: always
  ports:
    - 2368:2368
  env_file:
    - ./config.env
  volumes:
    - "./petemsGhost/content/:/usr/src/app/content/"
    - "./petemsGhost/config:/var/lib/ghost"
