version: '2'
services:
  db:
    container_name: postgres
    image: postgres:9.5.4
    env_file:
      - ./postgres/config.env
    volumes:
      - '/opt/docker/postgresql:/var/lib/postgresql'
  ghostblog:
    container_name: ghostblog
    build: ./petemsGhost/
    restart: always
    env_file:
      - ./petemsGhost/config.env
    volumes:
      - './petemsGhost/content/:/usr/src/app/content/'
      - './petemsGhost/config:/var/lib/ghost'
    ports:
      - 2368:2368
    links:
      - 'db:db'
